name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Clone the repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    # Build the project with Maven
    - name: Build with Maven
      run: mvn clean package -DskipTests

    # Deploy to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker stop e-learning-backend || true
          docker rm e-learning-backend || true
          cd /home/ubuntu/
          rm -f UserService-0.0.1-SNAPSHOT.jar
          exit

    # Copy JAR to EC2
    - name: Copy JAR to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: target/UserService-0.0.1-SNAPSHOT.jar
        target: /home/ubuntu/

    # Start Docker container
    - name: Run Docker Container
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ubuntu
          docker build -t e-learning-backend .
          docker run -d -p 8081:8081 --name e-learning-backend e-learning-backend
