name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Set up Java for Maven build
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    # 3️⃣ Build the project with Maven
    - name: Build with Maven
      run: mvn clean package -DskipTests

    # 4️⃣ Copy Dockerfile and project files to EC2
    - name: Copy project and Dockerfile to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "."
        target: "/home/ubuntu/backend-app"

    # 5️⃣ Run commands on EC2: Stop old container, build Docker image, run container
    - name: Deploy to EC2 and run Docker
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ubuntu/backend-app
          docker stop e-learning-backend || true
          docker rm e-learning-backend || true
          docker build -t e-learning-backend .
          docker run -d -p 8081:8081 --name e-learning-backend e-learning-backend
